# 在一条评论下面追加分数（即用时）并更新最高纪录

name: 更新计分板

on:
  workflow_dispatch:
    inputs:
      player:
        description: '玩家名'
        required: true
      rows:
        description: '行数'
        required: true
      cols:
        description: '列数'
        required: true
      score:
        description: '用时'
        required: true
      time:
        description: '时间'
        required: true

jobs:
  add_a_line:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get Comment
        uses: actions/github-script@v5
        id: get-comment
        with:
          script: |
            return (await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 995780464
            })).data.body;
          result-encoding: string
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: 生成新评论
        env:
          COMMENT: ${{ steps.get-comment.outputs.result }}
        run: |
          mkdir .idea
          echo "$COMMENT" > .idea/comment.txt
          echo "| ${{ github.event.inputs.player }} | ${{ github.event.inputs.rows }} | ${{ github.event.inputs.cols }} | ${{ github.event.inputs.score }} | ${{ github.event.inputs.time }} |" >> .idea/comment.txt
          python high-score.py
      - id: get-comment-body
        run: |
          body="$(cat .idea/processed.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"
      - name: 更新评论
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: 995780464
          edit-mode: replace
          body: ${{ steps.get-comment-body.outputs.body }}
