# 在一条评论下面追加分数（即用时）

name: 添加分数

on:
  workflow_dispatch:
    inputs:
      player:
        description: '玩家名'
        required: true
      rows:
        description: '行数'
        required: true
      cols:
        description: '列数'
        required: true
      score:
        description: '用时'
        required: true
      time:
        description: '时间'
        required: true

jobs:
  add_a_line:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 添加一行
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          comment-id: 986094230
          edit-mode: append
          body: |
            | <pre>${{ github.event.inputs.player }}</pre> | ${{ github.event.inputs.rows }} | ${{ github.event.inputs.cols }} | ${{ github.event.inputs.score }} | ${{ github.event.inputs.time }} |
