# 在一条评论下面追加分数（即用时）并更新最高纪录

name: 更新计分板

concurrency: updating-scoreboard

permissions:
  issues: write

on:
  workflow_dispatch:
    inputs:
      player_name:
        description: '玩家名'
        required: true
      rows:
        description: '行数'
        required: true
      cols:
        description: '列数'
        required: true
      score:
        description: '用时'
        required: true
      time:
        description: '时间'
        required: true

jobs:
  add-a-line:
    runs-on: ubuntu-latest
    steps:
      - name: Get Comment
        uses: actions/github-script@v5
        id: get-comment
        with:
          script: |
            return (await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 996055496
            })).data.body;
          result-encoding: string
      - run: wget https://raw.githubusercontent.com/plazum/find-keke/master/high-score.py
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: 生成新评论
        env:
          PLAYER_NAME: ${{ github.event.inputs.player_name }}
          ROWS: ${{ github.event.inputs.rows }}
          COLS: ${{ github.event.inputs.cols }}
          SCORE: ${{ github.event.inputs.score }}
          TIME: ${{ github.event.inputs.time }}
          COMMENT: ${{ steps.get-comment.outputs.result }}
        run: |
          mkdir .idea
          echo "$COMMENT" > .idea/comment.txt
          echo "| $PLAYER_NAME | $ROWS | $COLS | $SCORE | $TIME |"
          echo "| $PLAYER_NAME | $ROWS | $COLS | $SCORE | $TIME |" >> .idea/comment.txt
          python high-score.py
          ls -alFR
      - name: Get Comment Body
        id: get-comment-body
        run: |
          body="$(cat .idea/processed.txt)"
          body="${body//$'\n'/'\n'}"
          body="${body//$'\r'/'\r'}"
          echo "::set-output name=body::$body"
      - name: 更新评论
        uses: actions/github-script@v5
        env:
          BODY: ${{ steps.get-comment-body.outputs.body }}
        with:
          script: |
            let body = process.env.BODY.replace(/\\n/g, "\n").replace(/\\r/g, "\r");
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 996055496,
              body: body
            });
