# 在一条评论下面追加分数（即用时）

name: 添加分数

on:
  workflow_dispatch:
    inputs:
      player:
        description: '玩家名'
        required: true
      rows:
        description: '行数'
        required: true
      cols:
        description: '列数'
        required: true
      score:
        description: '用时'
        required: true
      time:
        description: '时间'
        required: true

jobs:
  add_a_line:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: 5
          body-includes: hoge fuga
      - name: 添加一行
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: 986094230
          edit-mode: append
          body: |
            | ${{ github.event.inputs.player }} | ${{ github.event.inputs.rows }} | ${{ github.event.inputs.cols }} | ${{ github.event.inputs.score }} | ${{ github.event.inputs.time }} |
      - env:
          COMMENT: ${{ steps.fc.outputs.comment-body }}
        run: |
          mkdir .idea
          echo "$COMMENT" > .idea/comment.txt
          echo "| ${{ github.event.inputs.player }} | ${{ github.event.inputs.rows }} | ${{ github.event.inputs.cols }} | ${{ github.event.inputs.score }} | ${{ github.event.inputs.time }} |" >> .idea/comment.txt
          cat .idea/comment.txt
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: 生成新评论
        run: |
          python high-score.py
      - id: get-comment-body
        run: |
          body="$(cat .idea/processed.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"
          echo '$body'
