# 重试被取消的workflow run

name: 重试更新计分板

on:
  workflow_dispatch:

jobs:
  re-run:
    runs-on: ubuntu-latest

    steps:
    - name: 重试
      uses: actions/github-script@v5
      with:
        script: |
          const r = (await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: "add-score.yml",
            status: "cancelled",
            per_page: 100,
            page: 1
          })).data;
          console.log(r.total_count);
          console.log(r.workflow_runs[r.total_count - 1]);
          const id = r.workflow_runs[r.total_count - 1].id;
          console.log(id);
          await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: id
          });
