name: Test

on: workflow_dispatch

jobs:
  find-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v5
        id: get-comment
        with:
          script: |
            return (await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 996055496
            })).data.body;
          result-encoding: string
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: 生成新评论
        env:
          COMMENT: ${{ steps.get-comment.outputs.result }}
          PLAYER_NAME: $$t"e's%t\\|`uname -a`
        run: |
          mkdir .idea
          echo "$COMMENT" > .idea/comment.txt
          echo "| $PLAYER_NAME | 14 | 10 | 0.00 | Thu Jan 01 1970 08:00:00 GMT+0800 (中国标准时间) |" >> .idea/comment.txt
          python high-score.py
      - id: get-comment-body
        run: |
          body="$(cat .idea/processed.txt)"
          # body="${body//'%'/'%25'}"
          body="${body//$'\n'/'\n'}"
          body="${body//$'\r'/'\r'}"
          body="${body//'"'/'\"'}"
          echo "::set-output name=body::$body"
      - name: 更新评论
        uses: actions/github-script@v5
        env:
          BODY: ${{ steps.get-comment-body.outputs.body }}
        with:
          script: |
            /*github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: 996055496,
              body: 
            })*/
            console.log(process.env);
